### ISSUE TITLE
Future of this fork

### ISSUE THREAD

**Issue by daniel-kukiela** [g588928812/bitsandbytes_jetsonX#2]
First, thank you very much for creating this fork and these fixes. It works fine on my Orin NX, but it took me a bit to make it work there, primarily because of some odd dependencies. Much appreciated <3

I'd like to ask about the future of this fork. I see that some tests are not passing and it's not updated with the newest code from the original repository. I would also like to see it on PyPi.
Do you plan to continue supporting this fork?

**Comment by g588928812** [comment]
Very welcome!
I've sold my jetson and got a computer with a proper GPU 😉 So I won't be maintaining this fork unfortunately

**Comment by daniel-kukiela** [comment]
Ah, gotcha :)
I may need to update this with the 0.39 updates to make it work with 4-bit quantization. Looks like I'll need to analyze your updates and try to merge the newest changes then :)

**Comment by sonebu** [comment]
sorry for bumping a closed thread, @daniel-kukiela have you carried out the update you mentioned in your last message? I'm after the same thing and would be happy to contribute if I can. Based on dusty's comments on the NVIDIA forums [here](https://forums.developer.nvidia.com/t/flash-attention-2-bitsandbytes-more/280793) I don't think we're going to see a pre-built version of this any time soon.

P.S. @g588928812 thanks a lot for this repo!

**Comment by sonebu** [comment]
I just realized dusty has actually made a follow-up fork of this repo and included the relevant changes there (merged 0.39.1, supports 4-bit inference etc.):
https://github.com/dusty-nv/bitsandbytes

I'll be using this one. @daniel-kukiela fyi
